contact_links:
  - name: Ask a question for self-hosting | 咨询自部署问题
    url: https://chat.imoogleai.xyz
    about: Please post questions, and ideas in discussions. | 请在讨论区发布问题和想法。
  - name: Questions and ideas | 其他问题和想法
    url: https://caht.imoogleai.xyz
    about: Please post questions, and ideas in discussions. | 请在讨论区发布问题和想法。
